version: '3.9'

services:
  postgres:
    image: postgres:${POSTGRES_TAG}
    restart: unless-stopped
    stop_grace_period: 10s
    environment:
      POSTGRES_DB: $POSTGRES_DB
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_USER: $POSTGRES_USER
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mysql:
    image: mysql:${MYSQL_TAG}
    restart: unless-stopped
    stop_grace_period: 10s
    environment: 
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_USER: $MYSQL_USER
      MYSQL_PASSWORD: $MYSQL_PASSWORD
    ports:
      - ${MYSQL_PORT}:3306
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer:${ADMINER_TAG}
    restart: unless-stopped
    stop_grace_period: 10s
    ports:
      - ${ADMINER_PORT}:8080

volumes:
  postgres-data: {}
  mysql-data: {}